export const mockNewDrops = [
  {
    id: '1',
    name: 'Air Jordan 1 Retro High OG',
    slug: 'air-jordan-1-retro-high-og',
    description: 'The legendary Air Jordan 1 returns with premium materials and classic colorway.',
    price: 15000,
    originalPrice: 18000,
    brand: 'Nike',
    category: 'footwear',
    gender: 'unisex',
    sizes: ['7', '8', '9', '10', '11', '12'],
    colors: ['Black/Red', 'White/Black'],
    images: ['https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800&h=800&fit=crop'],
    inStock: true,
    isOnSale: true,
    isNewArrival: true,
    tags: ['retro', 'basketball', 'iconic'],
  },
  {
    id: '2',
    name: 'Yeezy Boost 350 V2',
    slug: 'yeezy-boost-350-v2',
    description: "Kanye West's revolutionary sneaker with BOOST technology and Primeknit upper.",
    price: 12000,
    brand: 'Adidas',
    category: 'footwear',
    gender: 'unisex',
    sizes: ['6', '7', '8', '9', '10', '11'],
    colors: ['Cream', 'Black', 'Beluga'],
    images: ['https://images.unsplash.com/photo-1605348532760-6753d2c43329?w=800&h=800&fit=crop'],
    inStock: true,
    isOnSale: false,
    isNewArrival: true,
    tags: ['boost', 'casual', 'modern'],
  },
  {
    id: '3',
    name: 'Dunk Low "Panda"',
    slug: 'dunk-low-panda',
    description: "Nike's classic basketball-inspired sneaker in the iconic black and white colorway.",
    price: 8000,
    originalPrice: 10000,
    brand: 'Nike',
    category: 'footwear',
    gender: 'unisex',
    sizes: ['5', '6', '7', '8', '9', '10', '11'],
    colors: ['Black/White'],
    images: ['https://images.unsplash.com/photo-1549298916-b41d501d3772?w=800&h=800&fit=crop'],
    inStock: true,
    isOnSale: true,
    isNewArrival: true,
    tags: ['skate', 'casual', 'classic'],
  },
  {
    id: '4',
    name: 'New Balance 550',
    slug: 'new-balance-550',
    description: "Classic '90s basketball shoe revived with premium materials and retro styling.",
    price: 9500,
    brand: 'New Balance',
    category: 'footwear',
    gender: 'unisex',
    sizes: ['6', '7', '8', '9', '10', '11', '12'],
    colors: ['White/Green', 'White/Navy'],
    images: ['https://images.unsplash.com/photo-1605348532760-6753d2c43329?w=800&h=800&fit=crop'],
    inStock: true,
    isOnSale: false,
    isNewArrival: true,
    tags: ['retro', 'basketball', 'premium'],
  }
  ,
  {
    id: '10',
    name: 'Vans Old Skool',
    slug: 'vans-old-skool',
    description: 'Iconic skate shoe with durable canvas and suede upper, reinforced toe caps and signature side stripe.',
    price: 6500,
    brand: 'Vans',
    category: 'footwear',
    gender: 'unisex',
    sizes: ['4', '5', '6', '7', '8', '9', '10', '11'],
    colors: ['Black/White', 'Checkerboard'],
    images: ['https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=800&h=800&fit=crop'],
    inStock: true,
    isOnSale: false,
    isNewArrival: true,
    tags: ['skate', 'canvas', 'classic'],
  },
  {
    id: '11',
    name: 'Reebok Club C 85',
    slug: 'reebok-club-c-85',
    description: 'Minimalist leather sneaker with clean lines and heritage styling — versatile for casual and smart-casual outfits.',
    price: 7500,
    brand: 'Reebok',
    category: 'footwear',
    gender: 'unisex',
    sizes: ['6', '7', '8', '9', '10', '11'],
    colors: ['White', 'Off White'],
    images: ['https://images.unsplash.com/photo-1540574163026-643ea20ade25?w=800&h=800&fit=crop'],
    inStock: true,
    isOnSale: true,
    originalPrice: 9500,
    isNewArrival: true,
    tags: ['classic', 'tennis', 'minimal'],
  }
]

export const mockBestsellers = [
  {
    id: '5',
    name: "Air Force 1 '07",
    slug: 'air-force-1-07',
    description: 'The timeless Nike Air Force 1 with classic leather upper and Air-Sole unit.',
    price: 7500,
    brand: 'Nike',
    category: 'footwear',
    gender: 'unisex',
    sizes: ['6', '7', '8', '9', '10', '11', '12'],
    colors: ['White', 'Black', 'Triple Black'],
    images: ['https://images.unsplash.com/photo-1549298916-b41d501d3772?w=800&h=800&fit=crop'],
    inStock: true,
    isBestseller: true,
    tags: ['classic', 'leather', 'basketball'],
  },
  {
    id: '6',
    name: 'UltraBoost 22',
    slug: 'ultraboost-22',
    description: "Adidas' most responsive running shoe with BOOST midsole and Primeknit upper.",
    price: 11000,
    brand: 'Adidas',
    category: 'footwear',
    gender: 'unisex',
    sizes: ['6', '7', '8', '9', '10', '11', '12'],
    colors: ['Core Black', 'Cloud White', 'Blue'],
    images: ['https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?w=800&h=800&fit=crop'],
    inStock: true,
    isBestseller: true,
    tags: ['running', 'boost', 'performance'],
  },
  {
    id: '7',
    name: 'Chuck Taylor All Star',
    slug: 'chuck-taylor-all-star',
    description: 'The iconic Converse Chuck Taylor with classic canvas upper and rubber sole.',
    price: 4500,
    brand: 'Converse',
    category: 'footwear',
    gender: 'unisex',
    sizes: ['4', '5', '6', '7', '8', '9', '10', '11'],
    colors: ['Black', 'White', 'Red'],
    images: ['https://images.unsplash.com/photo-1525966222134-fcfa99b8ae77?w=800&h=800&fit=crop'],
    inStock: true,
    isBestseller: true,
    tags: ['canvas', 'classic', 'casual'],
  },
  {
    id: '8',
    name: 'Classic Leather',
    slug: 'classic-leather',
    description: "Reebok's timeless leather sneaker with vintage styling and comfortable fit.",
    price: 6500,
    brand: 'Reebok',
    category: 'footwear',
    gender: 'unisex',
    sizes: ['6', '7', '8', '9', '10', '11'],
    colors: ['White', 'Black', 'Navy'],
    images: ['https://images.unsplash.com/photo-1605348532760-6753d2c43329?w=800&h=800&fit=crop'],
    inStock: true,
    isBestseller: true,
    tags: ['leather', 'vintage', 'comfort'],
  }
  ,
  {
    id: '12',
    name: 'Nike Air Max 270',
    slug: 'nike-air-max-270',
    description: 'A modern silhouette with visible Air unit for maximum comfort; engineered for city life with breathable mesh and responsive cushioning.',
    price: 14000,
    brand: 'Nike',
    category: 'footwear',
    gender: 'unisex',
    sizes: ['6', '7', '8', '9', '10', '11', '12'],
    colors: ['Black/White', 'Infrared'],
    images: ['https://images.unsplash.com/photo-1528701800489-476a6c9b9a3d?w=800&h=800&fit=crop'],
    inStock: true,
    isBestseller: true,
    tags: ['air', 'running', 'comfort'],
  }
]

export const mockSaleProducts = [
  {
    id: '9',
    name: 'Air Max 90',
    slug: 'air-max-90',
    description: "Nike's classic Air Max 90 with visible Air cushioning and sleek design.",
    price: 6000,
    originalPrice: 9000,
    brand: 'Nike',
    category: 'footwear',
    gender: 'unisex',
    sizes: ['6', '7', '8', '9', '10', '11'],
    colors: ['White/Grey', 'Black/White', 'Infrared'],
    images: ['https://images.unsplash.com/photo-1543508282-6319a3e2621f?w=800&h=800&fit=crop'],
    inStock: true,
    isOnSale: true,
    tags: ['air-max', 'retro', 'cushioning'],
  }
  ,
  {
    id: '11a',
    name: 'Reebok Club C 85 (Sale)',
    slug: 'reebok-club-c-85-sale',
    description: 'Minimalist leather sneaker now on sale — clean lines and comfortable fit for everyday wear.',
    price: 5500,
    originalPrice: 7500,
    brand: 'Reebok',
    category: 'footwear',
    gender: 'unisex',
    sizes: ['6', '7', '8', '9', '10', '11'],
    colors: ['White'],
    images: ['https://images.unsplash.com/photo-1540574163026-643ea20ade25?w=800&h=800&fit=crop'],
    inStock: true,
    isOnSale: true,
    tags: ['sale', 'classic'],
  }
]

export const allProducts = [...mockNewDrops, ...mockBestsellers, ...mockSaleProducts]
